version: "3"
services:
  app:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html
    depends_on:
      - php
  php:
    build: ./docker/php
    volumes:
      - ./public_html:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    env_file: ./docker/php/.env.development
  mysql:
    build: ./docker/mysql
    env_file: ./docker/mysql/.env.development
