version: "3"
services:
  app:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html
    depends_on:
      - php
  php:
    image: php:7.3-fpm
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./public_html:/var/www/html